# Generated by Django 3.2.9 on 2021-12-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adviseme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='genre',
            field=models.TextField(choices=[('MOV', 'Movie'), ('BK', 'Book'), ('GM', 'Game')]),
        ),
    ]
