# Generated by Django 3.2.9 on 2021-12-06 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adviseme', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
